Bump the toolchain to 1.24.6
due to security analysis issue

```
Vulnerability #1: GO-2025-3956
    Unexpected paths returned from LookPath in os/exec
  More info: https://pkg.go.dev/vuln/GO-2025-3956
  Standard library
    Found in: os/exec@go1.24.4
    Fixed in: os/exec@go1.24.6
    Example traces found:
Error:       #1: frr-tools/metrics/vtysh/vtysh.go:14:26: vtysh.Run calls exec.Command, which calls exec.LookPath
```

Signed-off-by: Konstantinos Karampogias <karampok@gmail.com>