Remove duplicate relabings and metricRelabelings for speaker
Move metricRelabelings & relabelings for controller-monitor

Error when trying to use `relabelings` on ServiceMonitor:
```
Error: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(ServiceMonitor.spec): unknown field \"relabelings\" in com.coreos.monitoring.v1.ServiceMonitor.spec
```

On https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.63.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, `relabings` and `metricRelabelings` are only defined at one place.

Remove other part with relabings and metricRelabelings