All nodes will announce L2 services when speakerlist is disabled
Disabling speaker member list (via the Helm chart by setting
speaker.memberlist.enabled=false) means all speakers all nodes
will announce any l2 service.

The current implementation assumes there is no nodeSelector for speaker
daemonset and therefore all nodes have a speaker pod running.

```
helm template metallb ./charts/metallb \
       --set speaker.memberlist.enabled=false \
       --set speaker.nodeSelector.foo=bar

Error: execution error at (metallb/templates/speaker.yaml:12:4):
  nodeSelector must be empty when memberlist is disabled

```

Signed-off-by: karampok <karampok@gmail.com>