Added missing `group` to the validating webhook deploy kustomization
Otherwise it reports

```
Error: accumulating resources: recursed accumulation of path 'metallb/base/config/native': accumulating resources: recursed accumulation of path 'metallb/base/config/webhook': no matches for OriginalId ~G_v1_ValidatingWebhookConfiguration|~X|validating-webhook-configuration; no matches for CurrentId ~G_v1_ValidatingWebhookConfiguration|~X|validating-webhook-configuration; failed to find unique target for patch ~G_v1_ValidatingWebhookConfiguration|validating-webhook-configuration
```

for the `kustomize build ...`